services:
  - type: web
    name: yt-share-pwa-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: "false"
      - key: ALLOWED_ORIGINS
        sync: false
      - key: YOUTUBE_COLLECTOR_API_KEY
        sync: false
      - key: MQTT_BROKER
        sync: false
      - key: MQTT_PORT
        value: "1883"
      - key: MQTT_TOPIC
        value: youtube/jobs
